# Pandas: Grouping & Sorting

# Grouping in Pandas (`groupby`)

Grouping means splitting data into categories based on column values. Then we can apply operations (sum, mean, count, etc.) on each group.

In [1]:
import pandas as pd

In [2]:
data = {
    "OrderID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    "Customer": ["Alice","Bob","Charlie","Alice","Bob","David","Eve","Frank","Alice","Eve","Charlie","Bob","David","Frank","Alice"],
    "City": ["Bangalore","Chennai","Mumbai","Bangalore","Chennai","Delhi","Mumbai","Delhi","Bangalore","Mumbai","Mumbai","Chennai","Delhi","Delhi","Bangalore"],
    "Category": ["Electronics","Clothing","Electronics","Furniture","Electronics","Clothing","Furniture","Electronics","Clothing","Electronics","Furniture","Clothing","Electronics","Furniture","Electronics"],
    "Product": ["Laptop","Shirt","Mobile","Table","Headphones","Jacket","Chair","Tablet","T-shirt","Mobile","Sofa","Jeans","Laptop","Chair","Mobile"],
    "Quantity": [1,2,1,1,2,1,4,1,3,2,1,2,1,2,1],
    "Price": [60000,1500,20000,7000,3000,2500,5000,15000,800,22000,12000,1800,65000,5500,21000],
    "PaymentMode": ["UPI","Card","Cash","UPI","Card","Cash","UPI","Card","UPI","Cash","Card","UPI","Cash","Card","UPI"]
}

df = pd.DataFrame(data)
df

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI

In [3]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [4]:
df

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000

## Group by one column

In [5]:
df.groupby("City")

## Apply aggregation

In [6]:
# Average salary per department
df.groupby("City")["Revenue"].mean()

City
Bangalore    22600.0
Chennai       4200.0
Delhi        23375.0
Mumbai       24000.0
Name: Revenue, dtype: float64

## Apply Multiple aggregations

In [7]:
df.groupby("City")["Revenue"].agg(["min", "max", "mean", "sum", "count"])

             min    max     mean    sum  count
City
Bangalore   2400  60000  22600.0  90400      4
Chennai     3000   6000   4200.0  12600      3
Delhi       2500  65000  23375.0  93500      4
Mumbai     12000  44000  24000.0  96000      4

In [8]:
df.groupby("City")["Revenue"].agg(["mean"])

              mean
City
Bangalore  22600.0
Chennai     4200.0
Delhi      23375.0
Mumbai     24000.0

## Group by multiple columns

In [9]:
df.groupby(["City", "PaymentMode"])["Revenue"].sum()

City       PaymentMode
Bangalore  UPI            90400
Chennai    Card            9000
           UPI             3600
Delhi      Card           26000
           Cash           67500
Mumbai     Card           12000
           Cash           64000
           UPI            20000
Name: Revenue, dtype: int64

In [10]:
df.groupby(["City", "PaymentMode"])["Revenue"].agg(["sum"])

                         sum
City      PaymentMode
Bangalore UPI          90400
Chennai   Card          9000
          UPI           3600
Delhi     Card         26000
          Cash         67500
Mumbai    Card         12000
          Cash         64000
          UPI          20000

## Reset index
- `reset_index()` converts the grouped result into a DataFrame.

In [11]:
df.groupby("City")["Revenue"].mean().reset_index()

        City  Revenue
0  Bangalore  22600.0
1    Chennai   4200.0
2      Delhi  23375.0
3     Mumbai  24000.0

- Without `reset_index()`, we get a Series with City as index.

In [12]:
df.groupby("City")["Revenue"].mean()

City
Bangalore    22600.0
Chennai       4200.0
Delhi        23375.0
Mumbai       24000.0
Name: Revenue, dtype: float64

## Using `as_index=False`

In [13]:
# as_index=False → returns a DataFrame
df.groupby("City", as_index=False)["Revenue"].mean()

        City  Revenue
0  Bangalore  22600.0
1    Chennai   4200.0
2      Delhi  23375.0
3     Mumbai  24000.0

In [14]:
# default (as_index=True) → returns a Series with index
df.groupby("City", as_index=True)["Revenue"].mean()
# df.groupby("City")["Revenue"].mean()

City
Bangalore    22600.0
Chennai       4200.0
Delhi        23375.0
Mumbai       24000.0
Name: Revenue, dtype: float64

## Apply custom function

In [15]:
# Series
df.groupby("City")["Revenue"].apply(lambda x: x.max() - x.min())

City
Bangalore    57600
Chennai       3000
Delhi        62500
Mumbai       32000
Name: Revenue, dtype: int64

For each City, it calculates the Revenue range (highest Revenue − lowest Revenue). 

```python
.apply(lambda x: x.max() - x.min())
```
- `x` = all Revenues in that department
- `x.max()` = highest Revenue
- `x.min()` = lowest Revenue
- `subtract` → gives range

In [16]:
# Dataframe
df.groupby("City")["Revenue"].apply(lambda x: x.max() - x.min()).reset_index()

        City  Revenue
0  Bangalore    57600
1    Chennai     3000
2      Delhi    62500
3     Mumbai    32000

In [17]:
# Dataframe
df.groupby("City", as_index=False)["Revenue"].apply(lambda x: x.max() - x.min())

        City  Revenue
0  Bangalore    57600
1    Chennai     3000
2      Delhi    62500
3     Mumbai    32000

In [18]:
df.groupby("City")["Revenue"].agg(lambda x: x.max() - x.min())

City
Bangalore    57600
Chennai       3000
Delhi        62500
Mumbai       32000
Name: Revenue, dtype: int64

In [19]:
df.groupby("City")["Revenue"].agg(revenue_range=lambda x: x.max() - x.min())

           revenue_range
City
Bangalore          57600
Chennai             3000
Delhi              62500
Mumbai             32000

# Sorting in Pandas (`sort_values`, `sort_index`)

In [20]:
# Sorts in ascending order by default
df.sort_values("Revenue")

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000

In [21]:
# Sort descending
df.sort_values("Revenue", ascending=False)

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400

In [22]:
# Reset index after sorting
df.sort_values("Revenue", ascending=False).reset_index()

,index,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
0,12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
1,0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
2,9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
3,14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
4,2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
5,6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
6,7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
7,10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
8,13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
9,3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
10,4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
11,11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
12,1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
13,5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
14,8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400

In [23]:
# Reset index after sorting
df.sort_values("Revenue", ascending=False).reset_index(drop=True)

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
0,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
1,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
2,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
3,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
4,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
5,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
6,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
7,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
8,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
9,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
10,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
12,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
13,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
14,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400

In [24]:
# Sort by multiple columns
df.sort_values(["City", "Revenue"])

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000

In [25]:
# Different order for multiple columns
df.sort_values(["City", "Revenue"], ascending=[True, False])

,OrderID,Customer,City,Category,Product,Quantity,Price,PaymentMode,Revenue
0,101,Alice,Bangalore,Electronics,Laptop,1,60000,UPI,60000
14,115,Alice,Bangalore,Electronics,Mobile,1,21000,UPI,21000
3,104,Alice,Bangalore,Furniture,Table,1,7000,UPI,7000
8,109,Alice,Bangalore,Clothing,T-shirt,3,800,UPI,2400
4,105,Bob,Chennai,Electronics,Headphones,2,3000,Card,6000
11,112,Bob,Chennai,Clothing,Jeans,2,1800,UPI,3600
1,102,Bob,Chennai,Clothing,Shirt,2,1500,Card,3000
12,113,David,Delhi,Electronics,Laptop,1,65000,Cash,65000
7,108,Frank,Delhi,Electronics,Tablet,1,15000,Card,15000
13,114,Frank,Delhi,Furniture,Chair,2,5500,Card,11000
5,106,David,Delhi,Clothing,Jacket,1,2500,Cash,2500
9,110,Eve,Mumbai,Electronics,Mobile,2,22000,Cash,44000
2,103,Charlie,Mumbai,Electronics,Mobile,1,20000,Cash,20000
6,107,Eve,Mumbai,Furniture,Chair,4,5000,UPI,20000
10,111,Charlie,Mumbai,Furniture,Sofa,1,12000,Card,12000

## Grouping + Sorting Together

In [26]:
df.groupby("City", as_index=False)["Revenue"].mean() \
.sort_values("Revenue", ascending=False)

        City  Revenue
3     Mumbai  24000.0
2      Delhi  23375.0
0  Bangalore  22600.0
1    Chennai   4200.0