# Pandas : Indexing, Selecting & Assigning

# 1. Index

- Every DataFrame has row labels (index) and column labels.
- Default index: 0, 1, 2, ....
- Index helps in label-based data access.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [25, 30, 22]
})

In [3]:
df

  Name  Age
0    A   25
1    B   30
2    C   22

In [4]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [5]:
df.index.to_list()

[0, 1, 2]

# 2. Selecting Columns from DataFrame

## Single column → Series

In [6]:
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

## Single column → Dataframe

In [7]:
df[["Name"]]

  Name
0    A
1    B
2    C

## Multiple columns → DataFrame

In [8]:
df[["Name", "Age"]]

  Name  Age
0    A   25
1    B   30
2    C   22

# 3. Selecting Rows from DataFrame

## Using slicing

- This works like Python slicing.
- end excluded.

In [9]:
df[0:2]

  Name  Age
0    A   25
1    B   30

## `.loc[]` → Label-Based Selection

- Uses index labels.
- Includes end index.

In [10]:
# first row
df.loc[0]

Name     A
Age     25
Name: 0, dtype: object

In [11]:
# rows 0 to 2 (inclusive)
df.loc[0:2]

  Name  Age
0    A   25
1    B   30
2    C   22

In [12]:
# specific cell
df.loc[0, "Name"]

'A'

In [13]:
# Multiple selections
df.loc[[0, 2], ["Name", "Age"]]

  Name  Age
0    A   25
2    C   22

In [14]:
# Multiple selections
df.loc[0:2, ["Name", "Age"]]

  Name  Age
0    A   25
1    B   30
2    C   22

## `.iloc[]` → Position-Based Selection

- Uses integer positions.
- Works like Python indexing (end excluded).

In [15]:
# first row
df.iloc[0]

Name     A
Age     25
Name: 0, dtype: object

In [16]:
# rows 0 through to 2
df.iloc[0:3]

  Name  Age
0    A   25
1    B   30
2    C   22

In [17]:
# # specific cell : first row, second column
df.iloc[0, 1]

np.int64(25)

## `.loc` vs `.iloc`

| feature | `.loc` | `iloc` |
|:---|:---|:---|
| Based on | Labels | Positions |
| End index | Included | Excluded |

# 4. Boolean Indexing (Filtering)

In [18]:
df["Age"] > 23

0     True
1     True
2    False
Name: Age, dtype: bool

In [19]:
df[df["Age"] > 23]

  Name  Age
0    A   25
1    B   30

In [20]:
(df["Age"] > 22) & (df["Name"] == "B")

0    False
1     True
2    False
dtype: bool

In [21]:
df[(df["Age"] > 22) & (df["Name"] == "B")]

  Name  Age
1    B   30

# 5. Assigning / Modifying Data

## Assign New Column

In [22]:
df["Salary"] = [50000, 60000, 45000]

In [23]:
df

  Name  Age  Salary
0    A   25   50000
1    B   30   60000
2    C   22   45000

## Modify Existing Column

In [24]:
df["Age"] = df["Age"] + 1

In [25]:
df

  Name  Age  Salary
0    A   26   50000
1    B   31   60000
2    C   23   45000

## Conditional Assignment

In [26]:
df.loc[df["Age"] > 25, "Senior"] = True

In [27]:
df

  Name  Age  Salary Senior
0    A   26   50000   True
1    B   31   60000   True
2    C   23   45000    NaN

In [28]:
df.loc[df["Age"] > 30, "Salary"] = 70000

In [29]:
df

  Name  Age  Salary Senior
0    A   26   50000   True
1    B   31   70000   True
2    C   23   45000    NaN

## Assign Single Value

In [30]:
df.loc[0, "Age"] = 27

In [31]:
df

  Name  Age  Salary Senior
0    A   27   50000   True
1    B   31   70000   True
2    C   23   45000    NaN

# 6. Setting Custom Index

In [32]:
df

  Name  Age  Salary Senior
0    A   27   50000   True
1    B   31   70000   True
2    C   23   45000    NaN

In [33]:
df.set_index("Name", inplace=True)

In [34]:
df

      Age  Salary Senior
Name
A      27   50000   True
B      31   70000   True
C      23   45000    NaN

In [35]:
df.loc["A"]

Age          27
Salary    50000
Senior     True
Name: A, dtype: object

# 7. Resetting Index

In [36]:
df.reset_index()

  Name  Age  Salary Senior
0    A   27   50000   True
1    B   31   70000   True
2    C   23   45000    NaN

# 8. Examples

In [37]:
df = pd.DataFrame({
    "City": ["Bangalore", "Chennai", "Bangalore", "Mumbai"],
    "Revenue": [100, 200, 150, 300]
})
df

        City  Revenue
0  Bangalore      100
1    Chennai      200
2  Bangalore      150
3     Mumbai      300

In [38]:
# Filter Bangalore data
df[df["City"] == "Bangalore"]

        City  Revenue
0  Bangalore      100
2  Bangalore      150

In [39]:
# Increase revenue for Bangalore
df.loc[df["City"] == "Bangalore", "Revenue"] += 50

In [40]:
df

        City  Revenue
0  Bangalore      150
1    Chennai      200
2  Bangalore      200
3     Mumbai      300